{"overall": 5.0, "verified": true, "reviewTime": "10 20, 2014", "reviewerID": "A1D4G1SNUZWQOT", "asin": "7106116521", "reviewerName": "Tracy", "reviewText": "Exactly what I needed.", "summary": "perfect replacements!!", "unixReviewTime": 1413763200}
{"overall": 2.0, "vote": "3", "verified": true, "reviewTime": "09 28, 2014", "reviewerID": "A3DDWDH9PX2YX2", "asin": "7106116521", "reviewerName": "Sonja Lau", "reviewText": "I agree with the other review, the opening is too small.  I almost bent the hook on some very expensive earrings trying to get these up higher than just the end so they're not seen.  Would not buy again but for the price, not sending back.", "summary": "I agree with the other review, the opening is ...", "unixReviewTime": 1411862400}
{"overall": 4.0, "verified": false, "reviewTime": "08 25, 2014", "reviewerID": "A2MWC41EW7XL15", "asin": "7106116521", "reviewerName": "Kathleen", "reviewText": "Love these... I am going to order another pack to keep in work; someone (including myself) is always losing the back to an earring.  I don't understand why all fish hook earrings don't have them.  Just wish that they were a tiny bit longer.  :)", "summary": "My New 'Friends' !!", "unixReviewTime": 1408924800}
{"overall": 2.0, "verified": true, "reviewTime": "08 24, 2014", "reviewerID": "A2UH2QQ275NV45", "asin": "7106116521", "reviewerName": "Jodi Stoner", "reviewText": "too tiny an opening", "summary": "Two Stars", "unixReviewTime": 1408838400}
{"overall": 3.0, "verified": false, "reviewTime": "07 27, 2014", "reviewerID": "A89F3LQADZBS5", "asin": "7106116521", "reviewerName": "Alexander D.", "reviewText": "Okay", "summary": "Three Stars", "unixReviewTime": 1406419200}
{"overall": 5.0, "verified": true, "reviewTime": "07 19, 2014", "reviewerID": "A29HLOUW0NS0EH", "asin": "7106116521", "reviewerName": "Patricia R. Erwin", "reviewText": "Exactly what I wanted.", "summary": "Five Stars", "unixReviewTime": 1405728000}
{"overall": 4.0, "verified": true, "reviewTime": "05 31, 2014", "reviewerID": "A7QS961ROI6E0", "asin": "7106116521", "reviewerName": "REBECCA S LAYTON", "reviewText": "These little plastic backs work great.  No more loosing \"hook\" earrings!  Wish I had ordered these sooner before I had lost some of my favorite earrings!", "summary": "Works great!", "unixReviewTime": 1401494400}
{"overall": 3.0, "verified": true, "reviewTime": "09 22, 2013", "reviewerID": "A1BB77SEBQT8VX", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "Darrow H Ankrum II", "reviewText": "mother - in - law wanted it as a present for her sister. she liked it and said it would work.", "summary": "bought as a present", "unixReviewTime": 1379808000}
{"overall": 3.0, "verified": true, "reviewTime": "07 17, 2013", "reviewerID": "AHWOW7D1ABO9C", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "rosieO", "reviewText": "Item is of good quality. Looks great, too. But it does not fit 100's! But it can be stretched to fit them if you carefully push bottom of case with your fingers. Then shove in a pack of 100's(max) and level it out as you close case stretching case closed. Leave a pk.in it for month or so & was la! Buxton is usually a good quality product!", "summary": "Buxton heiress collection", "unixReviewTime": 1374019200}
{"overall": 3.0, "verified": true, "reviewTime": "04 13, 2013", "reviewerID": "AKS3GULZE0HFC", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "M. Waltman", "reviewText": "I had used my last el-cheapo fake leather cigarette case for SEVEN YEARS. It still closed completely but the plastic made to look like leather was literally falling off, so it was time for a new one. Cigarette cases for kings size cigs are not easy to come by these days I discovered, but I was thrilled to find this one on Amazon. It was a great price, REAL LEATHER, and even had the cool zipper pouch on the back. I was so excited to get my case and toss that other one! Well, within THREE DAYS one of the gold clasps literally broke off! I couldn't believe it! I tried to super glue it back on and was not successful. so, I still use the case but it doesn't close securely. I was very disappointed that my $3.00 plastic one lasted 7 years and this real nice leather one lasted 3 days!! But I still love the zipper pouch on the back, it's great for the spare key to my car because I will not go ANYWHERE without my cigarettes!", "summary": "Top Clasp Broke Within 3 days!", "unixReviewTime": 1365811200}
{"overall": 4.0, "verified": true, "reviewTime": "03 9, 2013", "reviewerID": "A38NS6NF6WPXS", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "BTDoxies", "reviewText": "This brand has been around a long time and you can count on good quality merchandise.  Held up well with no rips or stitching problems!", "summary": "BUXTON QUALITY!", "unixReviewTime": 1362787200}
{"overall": 2.0, "verified": true, "reviewTime": "01 27, 2013", "reviewerID": "A1KOKO3HTSAI1H", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "Robin Howard", "reviewText": "I smoke 100's and these are NOT made for them.  I can get my cigarettes in it but it won't close. I was very disappointed.", "summary": "Buxton Heiress Collection Black Leather Cigarette case", "unixReviewTime": 1359244800}
{"overall": 1.0, "verified": true, "reviewTime": "01 4, 2013", "reviewerID": "A1G3S57JGZNPCL", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "kimberly a schotthoefer", "reviewText": "cheap and cheesy, but i guess i could have expected that for the price, won't purchase another without seeing first", "summary": "inexpensive case", "unixReviewTime": 1357257600}
{"overall": 1.0, "verified": true, "reviewTime": "07 30, 2012", "reviewerID": "AGBL3TTP6GV4X", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "gallina", "reviewText": "I ordered a ladies cigarette case for my wife, and a pack of Marlboro 100's would not fit in the case!!!!  I was ripped off!!!  A cigarette case should be able to hold any cigarette pack!!!!  I will not do business with Silverhooks again!!!!\n\nIt's not even worth the postage to send it back!!!!\n\nDissatisfied big time!!!!", "summary": "i was ripped off!!!!", "unixReviewTime": 1343606400}
{"overall": 4.0, "vote": "2", "verified": true, "reviewTime": "03 12, 2010", "reviewerID": "A1Y36BSE9GKXLV", "asin": "B00007GDFV", "reviewerName": "Ms Irish", "reviewText": "Received the case in less than a week...was very satisfied with the product...only one problem...not really a problem with product, but with price as inside the product was a Buxton tag that showed sugg retail at $9.99 and I paid $11.99.  Hmmm...didn't quite understand this, but what are you going to do?!  Beware...as I think that had I gone to the Buxton web site I may have been able to obtain the same product for the sugg retail price.", "summary": "Great bargain", "unixReviewTime": 1268352000}
{"overall": 3.0, "verified": true, "reviewTime": "10 31, 2017", "reviewerID": "A1L1U968VNYVA4", "asin": "B00007GDFV", "style": {"Color:": " Black"}, "reviewerName": "J.G.", "reviewText": "Love it but it tore up shortly after I got it. I ordered two and they both tore at the part that connects to the metal. Great seller though. Very prompt.", "summary": "Love it but it tore up shortly after I got ...", "unixReviewTime": 1509408000}