# -*- coding: utf-8 -*-
"""TA_Grp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Ynn3dlLvK6Qytd8_-l9Fm9fokccJndt
"""

pip install json_lines

# Commented out IPython magic to ensure Python compatibility.
import json_lines 
import pandas as pd
import re
import string
# %matplotlib inline

X=[]; y=[]; z=[]
with open('review.jl', 'rb') as f: 
  for item in json_lines.reader(f):
    if (item != None or item != '') and 'reviewText' in item:
      X.append(item['asin']) 
      y.append(item['reviewText'])
      z.append(item['overall'])

data = {'ID': X,'Rating':z,'Review': y}
df = pd.DataFrame(data=data)
print(df)

def cleaning(text):
  text=text.lower()
  text=re.sub('\[.*?\],!','', text)
  text=re.sub('[%s]'% re.escape(string.punctuation),'',text)
  text=re.sub('\w*\d\w*','',text)
  return text

cleaned = lambda x: cleaning(x)

def cleaning2(text):
  text=text.lower()
  text=re.sub('[''""...]','', text)
  text=re.sub('\n','',text)
  return text

cleaned2 = lambda x: cleaning2(x)

df['Review']=pd.DataFrame(df.Review.apply(cleaned))
df['Review']=pd.DataFrame(df.Review.apply(cleaned2))
print(df)

a=[]; b=[]; c=[]
with open('product.jl', 'rb') as file: 
  for item in json_lines.reader(file):
    if (item != None or item != '') and 'title' in item:
      a.append(item['asin']) 
      b.append(item['title'])

pro = {'ID': a,'Product':b}
df_pro = pd.DataFrame(data=pro)
df_pro['Product']=pd.DataFrame(df_pro.Product.apply(cleaned))
df_pro['Product']=pd.DataFrame(df_pro.Product.apply(cleaned2))
print(df_pro)

result = pd.merge(df,df_pro[['ID','Product']],on='ID')
print(list(result))
print(result)

from google.colab import files
result.to_csv('result.csv') 
files.download('result.csv')